### ISSUE TITLE
Pin dependencies to stable & compatible version

### ISSUE THREAD

**Issue by kaustubhn** [P0W/option_strategies#4]
In requirements.txt add version to the dependencies, so that the depndencies are not breaking when the latest versions are released.

Suggested versions:
azure-functions==1.17.0
requests==2.31.0
py5paisa==0.7.2
black==23.7.0
pyotp==2.9.0
websockets==11.0.3
pymongo==4.4.1
python-telegram-bot==20.4
python-telegram-bot[job-queue]==20.4
redis==5.0.0

**Comment by P0W** [comment]
Cool, addressed this. thanks
